CREATE TABLE produtos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150)   NOT NULL,
    descricao     TEXT,
    preco         NUMERIC(12, 2) NOT NULL,
    estoque       INTEGER        NOT NULL DEFAULT 0,
    categoria     VARCHAR(80),
    ativo         BOOLEAN        NOT NULL DEFAULT TRUE,
    criado_por_id BIGINT         NOT NULL,
    criado_em     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_produtos_criado_por FOREIGN KEY (criado_por_id) REFERENCES usuarios (id),
    CONSTRAINT ck_produtos_preco CHECK (preco >= 0),
    CONSTRAINT ck_produtos_estoque CHECK (estoque >= 0)
);

CREATE INDEX idx_produtos_criado_por ON produtos (criado_por_id);
CREATE INDEX idx_produtos_categoria  ON produtos (categoria);