REATE TABLE carrinho_itens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT  NOT NULL,
    produto_id  BIGINT  NOT NULL,
    quantidade  INTEGER NOT NULL,

    CONSTRAINT fk_carrinho_itens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_carrinho_itens_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT uk_carrinho_itens_usuario_produto UNIQUE (usuario_id, produto_id),
    CONSTRAINT ck_carrinho_itens_quantidade CHECK (quantidade > 0)
);