CREATE TABLE pedidos
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id           BIGINT         NOT NULL,
    status               VARCHAR(30)    NOT NULL DEFAULT 'AGUARDANDO_PAGAMENTO',
    valor_total          NUMERIC(12, 2) NOT NULL,
    pagamento_id_gateway VARCHAR(100),
    qr_code              TEXT,
    criado_em            TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pago_em              TIMESTAMP,

    CONSTRAINT fk_pedidos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT uk_pedidos_pagamento_gateway UNIQUE (pagamento_id_gateway),
    CONSTRAINT ck_pedidos_status CHECK (status IN ('AGUARDANDO_PAGAMENTO', 'PAGO', 'CANCELADO', 'EXPIRADO')),
    CONSTRAINT ck_pedidos_valor_total CHECK (valor_total >= 0)
);