INSERT INTO perfis (nome)
SELECT 'ROLE_ADM' WHERE NOT EXISTS (SELECT 1 FROM perfis WHERE nome = 'ROLE_ADM');

INSERT INTO perfis (nome)
SELECT 'ROLE_CLIENT' WHERE NOT EXISTS (SELECT 1 FROM perfis WHERE nome = 'ROLE_CLIENT');