CREATE TABLE itens_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT         NOT NULL,
    produto_id     BIGINT         NOT NULL,
    quantidade     INTEGER        NOT NULL,
    preco_unitario NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_itens_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE CASCADE,
    CONSTRAINT fk_itens_pedido_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT uk_itens_pedido_pedido_produto UNIQUE (pedido_id, produto_id),
    CONSTRAINT ck_itens_pedido_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_itens_pedido_preco CHECK (preco_unitario >= 0)
);

CREATE INDEX idx_itens_pedido_produto ON itens_pedido (produto_id);